import re, os
import pandas as pd
import numpy as np

ROOT = r'C:\Users\dhl\data\Thesis\thesis\Thesis_Draft\Draft_v1\Tables'
prauc_path = os.path.join(ROOT, 'temporal_drift_analysis.tex')
lift_path = os.path.join(ROOT, 'temporal_drift_prauc_lift.tex')

def extract_matrix(path):
    with open(path, 'r') as f: lines = f.readlines()
    data = []
    eval_years = [2018, 2019, 2020, 2021, 2022, 2023, 2024]
    for line in lines:
        if "Pre-" in line and "---" in line or "0." in line or "1." in line or "2." in line or "3." in line or "4." in line or "5." in line or "6." in line or "7." in line or "8." in line or "9." in line:
            parts = line.strip().split('&')
            if len(parts) >= 8:
                model_anchor = parts[0].strip()
                if " " not in model_anchor: continue
                
                # Model name can have spaces like "Random Forest" or "Logistic (L2)"
                parts_ma = model_anchor.rsplit(' ', 1)
                model = parts_ma[0]
                anchor = parts_ma[1]
                
                vals = []
                for i, p in enumerate(parts[1:]):
                    p = p.replace('\\', '').replace('textbf{', '').replace('}', '').strip()
                    if p.strip() == "---":
                        vals.append(np.nan)
                    else:
                        vals.append(float(p))
                
                for i, v in enumerate(vals[:7]):
                    if not np.isnan(v):
                        data.append({
                            'Model': model,
                            'Anchor': anchor,
                            'Evaluate_Year': eval_years[i],
                            'Value': v
                        })
    return pd.DataFrame(data)

df_p = extract_matrix(prauc_path)
df_l = extract_matrix(lift_path)

def assign_family(model):
    if 'Logistic' in model: return 'Linear'
    if 'TabNet' in model: return 'Deep'
    return 'Trees'

if len(df_p) > 0:
    df_p['Family'] = df_p['Model'].apply(assign_family)
    df_l['Family'] = df_l['Model'].apply(assign_family)

    pivot_p = df_p.groupby(['Family', 'Anchor', 'Evaluate_Year'])['Value'].max().reset_index()
    pivot_mat_p = pivot_p.pivot_table(index='Family', columns=['Anchor', 'Evaluate_Year'], values='Value')
    winners_p = pivot_mat_p.idxmax()

    pivot_l = df_l.groupby(['Family', 'Anchor', 'Evaluate_Year'])['Value'].max().reset_index()
    pivot_mat_l = pivot_l.pivot_table(index='Family', columns=['Anchor', 'Evaluate_Year'], values='Value')
    winners_l = pivot_mat_l.idxmax()

    eval_years = [2018, 2019, 2020, 2021, 2022, 2023, 2024]
    anchors = ['Pre-2018', 'Pre-2019', 'Pre-2020', 'Pre-2021', 'Pre-2022', 'Pre-2023', 'Pre-2024']

    tex_lines = [
        r'\begin{table}[htbp]', r'\centering',
        r'\caption[Temporal Drift (Max-of-Family)]{\textbf{Max-of-Family architectural dominance.} Maximum absolute PR-AUC and PR-AUC Lift generated by either the linear baseline, non-linear tree ensembles, or deep architectures, highlighting the structural boundary of architectural capacity under domain shift.}',
        r'\label{tab:temporal_drift_family}', r'\resizebox{\textwidth}{!}{%',
        r'\begin{tabular}{l' + 'c'*len(eval_years) + '}', r'\toprule',
        r'\textbf{Anchor Training} & ' + ' & '.join(['\\textbf{' + str(y) + '}' for y in eval_years]) + r' \\',
        r'\midrule',
        r'\multicolumn{8}{c}{\textbf{Panel A: Maximum Absolute PR-AUC}} \\',
        r'\midrule'
    ]

    for anchor in anchors:
        row_sub = pivot_p[pivot_p['Anchor'] == anchor]
        if len(row_sub) == 0: continue
        r = []
        for test_year in eval_years:
            if test_year < int(anchor[-4:]): r.append("---")
            else:
                win_fam = winners_p.loc[(anchor, test_year)] if (anchor, test_year) in winners_p.index else None
                if win_fam is None or pd.isna(win_fam):
                    r.append("---")
                else:
                    max_val = pivot_mat_p.loc[win_fam, (anchor, test_year)]
                    r.append(f"{max_val:.3f} ({win_fam})")
        tex_lines.append(f"{anchor} & " + " & ".join(r) + r" \\")

    tex_lines.extend([
        r'\midrule',
        r'\multicolumn{8}{c}{\textbf{Panel B: Maximum Relative PR-AUC Lift}} \\',
        r'\midrule'
    ])

    for anchor in anchors:
        row_sub = pivot_l[pivot_l['Anchor'] == anchor]
        if len(row_sub) == 0: continue
        r = []
        for test_year in eval_years:
            if test_year < int(anchor[-4:]): r.append("---")
            else:
                win_fam = winners_l.loc[(anchor, test_year)] if (anchor, test_year) in winners_l.index else None
                if win_fam is None or pd.isna(win_fam):
                    r.append("---")
                else:
                    max_val = pivot_mat_l.loc[win_fam, (anchor, test_year)]
                    r.append(f"{max_val:.2f} ({win_fam})")
        tex_lines.append(f"{anchor} & " + " & ".join(r) + r" \\")

    tex_lines.extend([r'\bottomrule', r'\end{tabular}%', r'}', r'\end{table}'])

    with open(os.path.join(ROOT, 'temporal_drift_family.tex'), 'w') as f:
        f.write('\n'.join(tex_lines))
    print("New Family Matrix generated with Deep Architecture included!")
else:
    print("Failed to extract df")
